apiVersion: v1
kind: Service
metadata:
  name: iplaws
  labels:
    name: iplaws
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 1313
      protocol: TCP
  selector:
    name: iplaws
